key = input("Digite os caractéres que você deseja para criar a senha")

password = ""
for word in key:
    if word in "Aa": word += "0"
    elif word in "Bb": word += "1"
    elif word in "Cc": word += "2"
    elif word in "Dd": word += "3"
    elif word in "Ee": word += "4"
    elif word in "Ff": word += "5"
    elif word in "Gg": word += "6"
    elif word in "Hh": word += "7"
    elif word in "Ii": word += "8"
    elif word in "Jj": word += "9"
    elif word in "Kk": word += "@"
    elif word in "Ll": word += "#"
    elif word in "Mm": word += "!!"
    elif word in "Nn": word += "$"
    elif word in "Oo": word += "*"
    elif word in "Pp": word += "+"
    elif word in "Qq": word += "{"
    elif word in "Rr": word += "}"
    elif word in "Ss": word += "["
    elif word in "Tt": word += "]"
    elif word in "Uu": word += "^"
    elif word in "Vv": word += "~"
    elif word in "Ww": word += "/"
    elif word in "Xx": word += "?"
    elif word in "Yy": word += ";"
    elif word in "Zz": word += ".,"
    elif word in "Çç": word += "="
    elif word in "Nn": word += "1"
    elif word in "0": word += "a"
    elif word in "1": word += "b"
    elif word in "2": word += "c"
    elif word in "3": word += "d"
    elif word in "4": word += "e"
    elif word in "5": word += "f"
    elif word in "6": word += "g"
    elif word in "7": word += "h"
    elif word in "8": word += "g"
    elif word in "9": word += "i"

print(password)
